### ISSUE TITLE
Export OSM file to shapefile

### ISSUE THREAD

**Issue by hzhangic** [osmcode/osm-gis-export#2]
Hello Jochen, I installed osm-gis-export for exporting .osm.pbf files to shapefiles. Could you provide an example on how to do this? I have `osm_gis_export_overview, osmium_toogr, osmium_toogr2 and osmium_toogr2_exp` under the `/osm-gis-export/build/src` folder. Which one should I use? Thanks!

**Comment by joto** [comment]
Sorry, currently you have to look at the source code and change it according to your needs. This software can be used as basis for your own experiments, but you need to understand C++ for that. There is no one-size-fits-all solution here. Use  `osmium_toogr` as a basis if you only need nodes or ways, no (multi)polygons. Use `osmium_toogr2` as basis if you also need multipolygon support.
