### ISSUE TITLE
osmium_toogr2 core dump if called without arguments

### ISSUE THREAD

**Issue by wosch** [osmcode/osm-gis-export#6]
The tool osmium_toogr2 crash with a core dump if called without arguments:

~/osm-gis-export/build/src: ./osmium_toogr2
Pass 1...
terminate called after throwing an instance of 'osmium::io_error'
  what():  Could not detect file format for stdin/stdout.
Aborted (core dumped)

**Comment by wosch** [comment]
PS: same problem for the other tools:

~/osm-gis-export/build/src$ for i in osm*;do ./$i;done
terminate called after throwing an instance of 'osmium::io_error'
  what():  Could not detect file format for stdin/stdout.
Aborted (core dumped)
terminate called after throwing an instance of 'osmium::io_error'
  what():  Could not detect file format for stdin/stdout.
Aborted (core dumped)
Pass 1...
terminate called after throwing an instance of 'osmium::io_error'
  what():  Could not detect file format for stdin/stdout.
Aborted (core dumped)
terminate called after throwing an instance of 'osmium::io_error'
  what():  Could not detect file format for stdin/stdout.
Aborted (core dumped)

**Comment by joto** [comment]
This just needs a wrapper around most of the `main` function that catches the exception thrown and creates a nice error message and exits with an error code. Patches welcome.
