### ISSUE TITLE
osmium_toogr2 memory usage display

### ISSUE THREAD

**Issue by wosch** [osmcode/osm-gis-export#8]
osmium_toogr2 shows the number of used Memory:

$ ./osmium_toogr2 /tmp/a.xml 
Pass 1...
Pass 1 done
Pass 2...
Pass 2 done
Memory used: 623 MBytes

The 623 MBytes looks huge for an empty OSM XML file:

$ cat /tmp/a.xml 
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="Osmosis 0.46">
</osm>

I double-checked it with the linux time(1) command and the numbers are much lower, only 44MB res memory:

$ /usr/bin/time ./osmium_toogr2 /tmp/a.xml 
Pass 1...
Pass 1 done
Pass 2...
Pass 2 done
Memory used: 623 MBytes
0.06user 0.03system 0:00.10elapsed 100%CPU (0avgtext+0avgdata 44880maxresident)k
0inputs+6152outputs (0major+3308minor)pagefaults 0swaps

**Comment by joto** [comment]
The value reported is the `VmPeak` from `/proc/self/status` (https://github.com/osmcode/libosmium/blob/master/include/osmium/util/memory.hpp). Not sure where time(1) gets its data from and why that's different.

**Comment by wosch** [comment]
VmPeak is the virtual memory peak. The more important value is VmRSS, the maxresident usage.

The maxresident is the real used memory on the hardware.
https://en.wikipedia.org/wiki/Resident_set_size

The VM can be much higher than the RSS. This happens if you create a huge static array and using only the beginning part of it. As long as you do not modify the array, it is just virtual for the OS.

**Comment by joto** [comment]
What I use this number for is figuring out the worst case memory usage something has. So I can be forewarned when this is getting too big. And for that the VmPeak seems to be the right measurement for me.
